image: node:8.16.0

cache:
    paths:
        - node_modules/

stages:
    - build
    - deploy

build:
    stage: build
    tags: ["build"]
    script:
        - npm install
        - npm run gulp -- release
    only:
        - master
    artifacts:
        paths:
            - wwwroot/build

deploy:
    stage: deploy
    script:
        - bash ./etc/deploy/deploy.sh
    only:
        - master