image: node:8.16.0

cache:
    paths:
        - node_modules/

stages:
    - build
    - deploy

build:
    stage: build
    tags: ["build"]
    script:
        - npm install
        - npm run gulp -- release
    only:
        - master
    artifacts:
        paths:
            - wwwroot/build

deploy:
    stage: deploy
    variables:
        TRANSFER_PATH: ~/estadisticas/tmp/terria
        DEPLOY_TARGET_PATH: /servers/estadisticas/terria
    script:
        - scp -o ProxyCommand="ssh -W %h:%p deploy@estadisticas.arte-consultores.com" -r ./wwwroot deploy@192.168.10.16:$TRANSFER_PATH
        - ssh -o ProxyCommand="ssh -W %h:%p deploy@estadisticas.arte-consultores.com" deploy@192.168.10.16 "sudo rm -Rf $DEPLOY_TARGET_PATH/* && sudo mv $TRANSFER_PATH/* $DEPLOY_TARGET_PATH && sudo chown -R www-data:www-data $DEPLOY_TARGET_PATH && rm -rf $TRANSFER_PATH"
    only:
        - master